
package trabalhoprj.GUI;

import trabalhoprj.Classes.Venda;
import trabalhoprj.OperacaoCadastro;
import trabalhoprj.Modelos.ModeloTabelaVendas;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.TableRowSorter;
import trabalhoprj.Classes.ItemVenda;
import trabalhoprj.Executar.ImprimirTabelaVenda;
import trabalhoprj.Modelos.ModeloTabelaItemVenda;
import trabalhoprj.Modelos.ModeloTabelaProdutos;

public class GUI_Venda extends javax.swing.JDialog {
    private ModeloTabelaVendas modeloVendas;
    private TableRowSorter tableRowSorter;
    private ModeloTabelaItemVenda modeloItem;
    private ModeloTabelaProdutos modeloProduto;

    /**
     * Creates new form GUI_Outros
     */
    public GUI_Venda(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.getRootPane().setDefaultButton(buBuscar);
        modeloVendas = new ModeloTabelaVendas(new ArrayList<Venda>());
        modeloItem = new ModeloTabelaItemVenda(new ArrayList<ItemVenda>());
        tabVendas.setModel(modeloVendas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabVendas = new javax.swing.JTable();
        buIncluir = new javax.swing.JButton();
        buAlterar = new javax.swing.JButton();
        buExcluir = new javax.swing.JButton();
        buSelecionar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        edFiltro = new javax.swing.JTextField();
        buBuscar = new javax.swing.JButton();
        buImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        tabVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabVendas);

        buIncluir.setText("Incluir");
        buIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buIncluirActionPerformed(evt);
            }
        });

        buAlterar.setText("Alterar");
        buAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buAlterarActionPerformed(evt);
            }
        });

        buExcluir.setText("Excluir");
        buExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buExcluirActionPerformed(evt);
            }
        });

        buSelecionar.setText("Selecionar");
        buSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buSelecionarActionPerformed(evt);
            }
        });

        jLabel1.setText("Filtragem:");

        edFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edFiltroKeyTyped(evt);
            }
        });

        buBuscar.setText("Buscar");
        buBuscar.setToolTipText("");
        buBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buBuscarActionPerformed(evt);
            }
        });

        buImprimir.setText("Imprimir");
        buImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edFiltro))
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buSelecionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buAlterar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buImprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buIncluir)
                        .addGap(11, 11, 11)
                        .addComponent(buAlterar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buExcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                        .addComponent(buImprimir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buSelecionar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buIncluirActionPerformed
    Venda venda = new Venda();
    if (JanelaVenda.executar(null, OperacaoCadastro.ocIncluir, venda)){
        modeloVendas.incluirVenda(venda);
        }
    }//GEN-LAST:event_buIncluirActionPerformed

    private void buAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buAlterarActionPerformed
    int index = tabVendas.getSelectedRow();
    if (index >= 0){
        Venda venda = modeloVendas.obterVenda(index);
        if (JanelaVenda.executar(null, OperacaoCadastro.ocAlterar, venda)){
            modeloVendas.atualizarVenda(index, venda);
            }
        }
    }//GEN-LAST:event_buAlterarActionPerformed

    private void buExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buExcluirActionPerformed
    int index = tabVendas.getSelectedRow();
    if (index >= 0){
        JFrame frame = new JFrame("Excluir");
        Venda venda = modeloVendas.obterVenda(index);
        ItemVenda itemvenda = modeloItem.acharItemVenda(venda.obterCodigoVenda());
        int Resposta = JOptionPane.showConfirmDialog(frame,"Deseja excluir o cadastro?", "", JOptionPane.YES_NO_OPTION);
        if (Resposta == JOptionPane.YES_OPTION) {
            modeloVendas.excluirVenda(index, venda);
            modeloItem.excluirItemVenda(index, itemvenda);
            }
        }
    }//GEN-LAST:event_buExcluirActionPerformed

    private void buSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buSelecionarActionPerformed
        int index = tabVendas.getSelectedRow();
        if (index >= 0){
            Venda venda = modeloVendas.obterVenda(index);
            JanelaVenda.executar(null, OperacaoCadastro.ocConsultar, venda);
        }
    }//GEN-LAST:event_buSelecionarActionPerformed

    private void edFiltroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edFiltroKeyTyped

    }//GEN-LAST:event_edFiltroKeyTyped

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (modeloVendas.getRowCount() >= 0) {
            modeloVendas.carregar();
        }
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

    }//GEN-LAST:event_formWindowClosed

    private void buBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buBuscarActionPerformed
        tableRowSorter = new TableRowSorter(modeloVendas);
        tableRowSorter.setRowFilter(RowFilter.regexFilter( "(?i)" + edFiltro.getText(),0,1,2));
        tabVendas.setRowSorter(tableRowSorter);
    }//GEN-LAST:event_buBuscarActionPerformed

    private void buImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buImprimirActionPerformed
        float cartao = modeloVendas.calcularCartao();
        float dinheiro = modeloVendas.calcularDinheiro();
        new ImprimirTabelaVenda(tabVendas,dinheiro,cartao);
    }//GEN-LAST:event_buImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GUI_Venda dialog = new GUI_Venda(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buAlterar;
    private javax.swing.JButton buBuscar;
    private javax.swing.JButton buExcluir;
    private javax.swing.JButton buImprimir;
    private javax.swing.JButton buIncluir;
    private javax.swing.JButton buSelecionar;
    private javax.swing.JTextField edFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabVendas;
    // End of variables declaration//GEN-END:variables
}
