
package trabalhoprj.GUI;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

public class JanelaMenus extends javax.swing.JFrame {
    /**
     * Creates new form JanelaMenus
     */
    public JanelaMenus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        ArquivoBarra = new javax.swing.JMenu();
        FecharMenu = new javax.swing.JMenuItem();
        CadastroBarra = new javax.swing.JMenu();
        ProdutosMenu = new javax.swing.JMenuItem();
        ClientesMenu = new javax.swing.JMenuItem();
        Vendas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        ArquivoBarra.setText("Arquivo");

        FecharMenu.setText("Fechar");
        FecharMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FecharMenuActionPerformed(evt);
            }
        });
        ArquivoBarra.add(FecharMenu);

        jMenuBar1.add(ArquivoBarra);

        CadastroBarra.setText("Cadastro");

        ProdutosMenu.setText("Produtos");
        ProdutosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProdutosMenuActionPerformed(evt);
            }
        });
        CadastroBarra.add(ProdutosMenu);

        ClientesMenu.setText("Clientes");
        ClientesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientesMenuActionPerformed(evt);
            }
        });
        CadastroBarra.add(ClientesMenu);

        Vendas.setText("Vendas");
        Vendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VendasActionPerformed(evt);
            }
        });
        CadastroBarra.add(Vendas);

        jMenuBar1.add(CadastroBarra);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FecharMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FecharMenuActionPerformed
        dispose();
    }//GEN-LAST:event_FecharMenuActionPerformed

    private void ProdutosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProdutosMenuActionPerformed
        GUI_Produto quadroDialogo = new GUI_Produto(null, true);
        quadroDialogo.setLocationRelativeTo(null);
        quadroDialogo.setVisible(true);
    }//GEN-LAST:event_ProdutosMenuActionPerformed

    private void ClientesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientesMenuActionPerformed
        GUI_Cliente quadroDialogo = new GUI_Cliente(null, true);
        quadroDialogo.setLocationRelativeTo(null);
        quadroDialogo.setVisible(true);
    }//GEN-LAST:event_ClientesMenuActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void VendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VendasActionPerformed
        GUI_Venda quadroDialogo = new GUI_Venda(null, true);
        quadroDialogo.setLocationRelativeTo(null);
        quadroDialogo.setVisible(true);            
    }//GEN-LAST:event_VendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaMenus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaMenus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ArquivoBarra;
    private javax.swing.JMenu CadastroBarra;
    private javax.swing.JMenuItem ClientesMenu;
    private javax.swing.JMenuItem FecharMenu;
    private javax.swing.JMenuItem ProdutosMenu;
    private javax.swing.JMenuItem Vendas;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
